[package]
name = "cmake-fmt"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.7", features = ["derive"] }
thiserror = "1.0.50"
tree-sitter = "0.20.10"
tree-sitter-cmake = "0.4.0"
